### ISSUE TITLE
NameError at /registerhook

### ISSUE THREAD

**Issue by zachallett** [StephenOTT/GitHub-Reminders#3]
I received `NameError at /registerhook` when trying to register a repository. I'm not sure if it impacts anything, but the repository is brand new and located at https://github.com/zhallett/testing-reminders

![screen shot 2014-07-08 at 2 44 17 pm](https://cloud.githubusercontent.com/assets/1425271/3514866/2c24a872-06d0-11e4-9e39-147c81018f9a.png)

**Comment by StephenOTT** [comment]
!@#!

Okay fixed.  That was a typo on my side.  Should never drink and code, and not check your work the next day.

Give it another try!!

**Comment by zachallett** [comment]
I was able to register it via github-reminders.com, however on my repository webhooks section I see:

![screen shot 2014-07-08 at 3 11 22 pm](https://cloud.githubusercontent.com/assets/1425271/3515210/b0c4e6fc-06d3-11e4-824d-09f74bc74ef1.png)

**Comment by StephenOTT** [comment]
that may just be heroku being slow on the free instance.  Can you select the hook/edit the hook and show me the screenshot?

**Comment by StephenOTT** [comment]
Go create a new comment in a issue

**Comment by zachallett** [comment]
Here is the screenshot of the edit view for the hook:

Link for 2nd reminder: https://github.com/zhallett/testing-reminders/issues/2

![screen shot 2014-07-08 at 3 15 01 pm](https://cloud.githubusercontent.com/assets/1425271/3515258/389b88e2-06d4-11e4-88fe-d10ef75fcd5b.png)

**Comment by StephenOTT** [comment]
click on the item in the recent deliverables and resend it

**Comment by zachallett** [comment]
I see a passing payload from you on the comment you left. When I try to re-deliver the first, I still see an error 500 with this being the payload:

![screen shot 2014-07-08 at 3 18 00 pm](https://cloud.githubusercontent.com/assets/1425271/3515310/acad5eae-06d4-11e4-9e59-45290bb7b987.png)

**Comment by StephenOTT2** [comment]
That should be fine.  Go and make a comment in your issue

**Comment by StephenOTT2** [comment]
The first ping won't go through

**Comment by StephenOTT** [comment]
Should be working now.  I am seeing the reminder coming up in the app

**Comment by zachallett** [comment]
Yup, saw it come through my inbox

**Comment by StephenOTT** [comment]
![screen shot 2014-07-08 at 3 27 54 pm](https://cloud.githubusercontent.com/assets/1994838/3515455/ff110208-06d5-11e4-8303-70cadbc6f29c.png)

email UI needs work :)  As said.  Very beta.

**Comment by StephenOTT** [comment]
There also seems to be a weird double hit from GH.com on the Reminders.com web hook.  at times i see two reminders being created for a single comment.  This would only occur if the API api was called twice.  Will monitor that.

**Comment by zachallett** [comment]
I'll see if I can't poke around and see if I can offer anything in terms of the codebase if you don't mind

**Comment by StephenOTT** [comment]
No problem at all.  was built to be pretty flexible.  You will have to go to the Worker to edit the email template: https://github.com/StephenOTT/GitHub-Reminders-Worker

specifically: https://github.com/StephenOTT/GitHub-Reminders-Worker/blob/master/email_templates/reminder.html.erb

All the variables are already in the template.  Just needs better styling.

**Comment by StephenOTT** [comment]
using: http://internations.github.io/antwort/ for the email template framework
